name: Github TO Gitee:master
on: [push]
jobs:
#  get-gitee-code:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Mirror the Github organization repos to Gitee.
#      uses: Yikun/hub-mirror-action@master
#      with:
#        src: github/kunpengcompute
#        dst: gitee/kunpengcompute
#        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#        dst_token: ${{ secrets.GITEE_TOKEN }}
#        account_type: org
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Use Node@14.x # 步骤2
      uses: actions/setup-node@v1 # 作用：安装nodejs
      with:
        node-version: 10.14.1
        
    
    - name: Install
      run: npm install

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # 你要操作的目标仓库
        TARGET_REPO: meliauk/ddbug
        # 构建结果存储的分支
        TARGET_BRANCH: pages
        # 要使用的构建命令
        BUILD_SCRIPT: gitbook build
        # 构建结果存储目录
        BUILD_DIR: _book 
  sync:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITBOOK_RSA_PRIVATE_KEY }}
      with:
        # 来源仓库
        source-repo: "git@github.com:meliauk/ddbug.git"
        # 目标仓库
        destination-repo: "git@gitee.com:MEliauk/ddbug.git"
  reload-pages:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: MEliauk
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: MEliauk/ddbug
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: pages
