name: Github TO Gitee:master
on: [push]
jobs:
#  get-gitee-code:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Mirror the Github organization repos to Gitee.
#      uses: Yikun/hub-mirror-action@master
#      with:
#        src: github/kunpengcompute
#        dst: gitee/kunpengcompute
#        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#        dst_token: ${{ secrets.GITEE_TOKEN }}
#        account_type: org
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Use Node@10.x # 步骤2
      uses: actions/setup-node@v1 # 作用：安装nodejs
      with:
        node-version: 10.14.1
        
    - name: Set node version to ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'
    
    - name: Install gitbook
      run: npm install -g gitbook-cli
      
    # Install dependencies for build process
    - name: Install build dependencies
      run: |
        gitbook build
        git add .
        git commit -m "actions commit"
        git push origin master
