name: 同步到gitee并page
on: [push]
jobs:
  # get-gitee-code:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Sync to Gitee
  #     uses: Yikun/hub-mirror-action@master
  #     with:
  #       src: gitee/MEliauk
  #       dst: github/meliauk
  #       dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
  #       dst_token: ${{ secrets.GITBUB_TOKEN }}
  #       static_list: "ddbug"
        
  build-and-push:
    permissions:
        contents: write
        id-token: write
        pull-requests: write
        issues: write
        repository-projects: write
        deployments: write
        packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Use Node@10.14.1 # 步骤2
      uses: actions/setup-node@v1 # 作用：安装nodejs
      with:
        node-version: 10.14.1
        
    - name: Set node version to ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'
    
    - name: Install gitbook
      run: npm install -g gitbook-cli
      
    - name: Install gitbook-plugin-lightbox
      run: npm install gitbook-plugin-lightbox

    - name: gitbook install
      run: gitbook install 

    - name: gitbook build
      run: gitbook build 

    - name: CommitPush
      run: |
        git config --global user.email 2050781802@qq.com
        git config --global user.name meliauk
        git add .
        git commit -m"action:`date`"
        git pull
        git push -f origin master
  sync:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/meliauk
        dst: gitee/MEliauk
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "ddbug"
  reload-pages:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: MEliauk
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错  
          gitee-repo: MEliauk/ddbug
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master
          directory: _book
